window.releasedResources = {
  "day-01-hybrid-notes": true,
  "day-01-handout": true,
  "day-01-practice": true,
  "day-01-exit-slip": false,
  "day-01-assessment": false,

  "day-02-hybrid-notes": true,
  "day-02-handout": true,
  "day-02-practice": true,
  "day-02-exit-slip": false,
  "day-02-assessment": false,

  "day-03-hybrid-notes": true,
  "day-03-handout": true,
  "day-03-practice": true,
  "day-03-exit-slip": false,
  "day-03-assessment": false,

  "day-04-hybrid-notes": true,
  "day-04-handout": true,
  "day-04-practice": true,
  "day-04-exit-slip": false,
  "day-04-assessment": false,

  "day-05-hybrid-notes": true,
  "day-05-handout": true,
  "day-05-practice": true,
  "day-05-exit-slip": false,
  "day-05-assessment": false,

  "day-06-hybrid-notes": true,
  "day-06-handout": true,
  "day-06-practice": true,
  "day-06-exit-slip": false,
  "day-06-assessment": false,

  "day-07-hybrid-notes": true,
  "day-07-handout": true,
  "day-07-notes": true,
  "day-07-practice": true,
  "day-07-exit-slip": false,
  "day-07-assessment": false,

  "day-08-hybrid-notes": true,
  "day-08-handout": true,
  "day-08-notes": true,
  "day-08-practice": true,
  "day-08-exit-slip": false,
  "day-08-assessment": false,

  "day-09-handout": true,
  "day-09-notes": true,
  "day-09-hybrid-notes": true,
  "day-09-practice": true,
  "day-09-exit-slip": false,
  "day-09-assessment": false,

  "day-10-handout": true,
  "day-10-notes": true,
  "day-10-hybrid-notes": true,
  "day-10-practice": true,
  "day-10-exit-slip": false,
  "day-10-assessment": false,

  "day-11-hybrid-notes": true,
  "day-11-handout": true,
  "day-11-practice": true,
  "day-11-exit-slip": false,
  "day-11-assessment": false,

  "day-12-hybrid-notes": true,
  "day-12-handout": true,
  "day-12-practice": true,
  "day-12-exit-slip": false,
  "day-12-assessment": false,

  "day-13-hybrid-notes": true,
  "day-13-handout": true,
  "day-13-practice": true,
  "day-13-exit-slip": false,
  "day-13-assessment": false,

  "day-14-hybrid-notes": true,
  "day-14-handout": true,
  "day-14-practice": true,
  "day-14-exit-slip": false,
  "day-14-assessment": false,

  "day-15-hybrid-notes": true,
  "day-15-handout": true,
  "day-15-practice": true,
  "day-15-exit-slip": false,
  "day-15-assessment": false,

  "day-16-hybrid-notes": true,
  "day-16-handout": true,
  "day-16-practice": true,
  "day-16-exit-slip": false,
  "day-16-assessment": false,

  "day-17-hybrid-notes": true,
  "day-17-handout": true,
  "day-17-practice": true,
  "day-17-exit-slip": false,
  "day-17-assessment": false,

  "day-18-hybrid-notes": true,
  "day-18-handout": true,
  "day-18-practice": true,
  "day-18-exit-slip": false,
  "day-18-assessment": false,

  "day-19-hybrid-notes": true,
  "day-19-handout": true,
  "day-19-practice": true,
  "day-19-exit-slip": false,
  "day-19-assessment": false,

  "day-20-hybrid-notes": true,
  "day-20-handout": true,
  "day-20-practice": true,
  "day-20-exit-slip": false,
  "day-20-assessment": false,

  "day-21-hybrid-notes": true,
  "day-21-handout": true,
  "day-21-practice": true,
  "day-21-exit-slip": false,
  "day-21-assessment": false,

  "day-22-hybrid-notes": true,
  "day-22-handout": true,
  "day-22-practice": true,
  "day-22-exit-slip": false,
  "day-22-assessment": false,

  "day-23-hybrid-notes": true,
  "day-23-handout": true,
  "day-23-practice": true,
  "day-23-exit-slip": false,
  "day-23-assessment": false,

  "day-24-hybrid-notes": true,
  "day-24-handout": true,
  "day-24-practice": true,
  "day-24-exit-slip": false,
  "day-24-assessment": false,

  "day-25-hybrid-notes": true,
  "day-25-handout": true,
  "day-25-practice": true,
  "day-25-exit-slip": false,
  "day-25-assessment": false,

  "day-26-hybrid-notes": true,
  "day-26-handout": true,
  "day-26-practice": true,
  "day-26-exit-slip": false,
  "day-26-assessment": false,
};
